# Generated by Django 4.1 on 2025-08-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, unique=True, verbose_name='邮箱')),
            ],
        ),
    ]
