# Generated by Django 4.1 on 2025-08-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户名', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
